name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 9 * * *'

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Install dependence
      run: sudo apt-get install -y cmake ninja-build nodejs
    - name: Update wabt
      run: git clone https://github.com/WebAssembly/wabt
    - name: Build wabt
      working-directory: wabt
      run: git submodule update --init &&  mkdir build && cd build && cmake .. && cmake --build .
    - name: Update testsuite
      run: git clone https://github.com/WebAssembly/testsuite
    - name: Build testsuite
      working-directory: testsuite
      run: git submodule update --init && bash ./extract-parts.sh
    - name: Generate page
      run: npm i && npm run build
    - uses: EndBug/add-and-commit@v9
      with:
        add: 'src/*.html'
        new_branch: release
        message: build by github action
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
