name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '0 9 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependence
      run: sudo apt-get install -y cmake ninja-build nodejs
    - name: Update wabt
      run: git clone https://github.com/WebAssembly/wabt
    - name: Build wabt
      working-directory: wabt
      run: git submodule update --init &&  mkdir build && cd build && cmake .. && cmake --build .
    - name: Update testsuite
      run: git clone https://github.com/WebAssembly/testsuite
    - name: Build testsuite
      working-directory: testsuite
      run: git submodule update --init && bash ./extract-parts.sh
    - name: Generate page
      run: npm run build
